export {default as NavBar} from "./NavBar"
export {default as CryptoCurrencies} from "./CryptoCurrencies"
export {default as CryptoDetails} from "./CryptoDetails"
export {default as News} from "./News"
export {default as HomePage} from "./HomePage"
export {default as Exchanges} from "./Exchanges"